server:
  port: 8183

spring :
  application :
    name : ApiGateway

  cloud:
    gateway:
      routes:
        - id: UserService
          uri: http://localhost:8181
          predicates:
            - Path=/Auth/v1/api/**
eureka:
  client:
    fetch-registry : true
    register-with-eureka : true
    service-url:
      defaultZone : http://localhost:8182/eureka/
